# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'PillBox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Auth'

  # Pods for PillBox

  target 'PillBoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PillBoxUITests' do
    # Pods for testing
  end

end
